name: Playwright Tests with Allure Report

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18  # Explicit version for consistency

      - name: Install Dependencies
        run: npm install

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Playwright Tests with Allure
        run: npx playwright test --reporter=allure-playwright

      - name: Generate Allure Report
        run: |
          npx allure generate allure-results --clean -o allure-report
          touch allure-report/.nojekyll  # Fix for GitHub Pages

      - name: Upload Allure Report Artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: allure-report

  deploy:
    needs: test
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write

    steps:
      - name: Deploy Allure Report to GitHub Pages
        uses: actions/deploy-pages@v2

      - name: Send Allure Report Link via Email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USER }}
          password: ${{ secrets.EMAIL_PASS }}
          subject: "📊 Playwright Allure Test Report"
          body: |
            Hello,

            The latest Playwright Allure Report is available at:
            https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/index.html

            Best,
            GitHub Actions
          from: "GitHub Actions <${{ secrets.EMAIL_USER }}>"
          to: ${{ secrets.EMAIL_RECEIVER }}
