name: Playwright Tests with Allure

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - uses: actions/checkout@v4

      # Setup Node.js
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*

      # Install dependencies
      - name: Install dependencies
        run: npm ci

      # Install Playwright Browsers
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      # Install Allure dependencies & required packages
      - name: Install Allure & Email Dependencies
        run: |
          npm i -D @playwright/test allure-playwright
          npm i -g allure-commandline ts-node
          npm i nodemailer archiver dotenv

      # Run Playwright Tests with Allure Reporter
      - name: Run Playwright tests
        run: npx playwright test --reporter=allure-playwright

      # Generate Allure Report
      - name: Generate Allure Report
        run: allure generate allure-results -o allure-report --clean

      # Upload Allure Report as Artifact
      - name: Upload Allure Report
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: allure-report/
          retention-days: 30

      # Send Allure Report via Email
     - name: Send Allure Report Email
  env:
    EMAIL_USER: ${{ secrets.EMAIL_USER }}
    EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
    EMAIL_RECEIVER: ${{ secrets.EMAIL_RECEIVER }}
    GITHUB_RUN_ID: ${{ github.run_id }}
    GITHUB_REPOSITORY: ${{ github.repository }}
  run: npx ts-node utils/sendEmail.ts
