name: Playwright Tests with Allure Report

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:
  page_build:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: lts/*

      - name: Install Dependencies
        run: npm install

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      # ✅ Install Allure dependencies & required packages
      - name: Install Allure & Email Dependencies
        run: |
          npm i -D @playwright/test allure-playwright
          npm i -g allure-commandline ts-node
          npm i nodemailer archiver dotenv
      - name: Run Playwright Tests with Allure
        run: npx playwright test --reporter=allure-playwright

      - name: Generate Allure Report
        run: |
          allure generate allure-results -o allure-report --clean
          touch allure-report/.nojekyll

      - name: Verify Allure Report Content
        run: ls -la allure-report

      # ✅ Use consistent artifact name
      - name: Upload Allure Report Artifact
        uses: actions/upload-artifact@v4
        with:
          name: github-pages   # Consistent name used here
          path: allure-report

  deploy:
    needs: test
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      # ✅ Download the uploaded artifact with correct name
      - name: Download Allure Report Artifact
        uses: actions/download-artifact@v4
        with:
          name: github-pages  # Matches the upload step
          path: allure-report
      - name: Verify Downloaded Artifact
        run: ls -la allure-report
      # ✅ Deploy Allure Report to GitHub Pages
      - name: Deploy Allure Report to GitHub Pages
        uses: actions/deploy-pages@v2
        with:
          artifact_name: github-pages 

      # ✅ Send Allure Report Link via Email
      - name: Send Allure Report Link via Email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USER }}
          password: ${{ secrets.EMAIL_PASS }}
          subject: "📊 Playwright Allure Test Report"
          body: |
            Hello,
            The latest Playwright Allure Report is available at:
            https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/index.html
            Best,
            GitHub Actions
          from: "GitHub Actions <${{ secrets.EMAIL_USER }}>"
          to: ${{ secrets.EMAIL_RECEIVER }}