name: Deploy Allure Report to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Download Allure Report Artifact
        uses: actions/download-artifact@v4
        with:
          name: github-pages
          path: allure-report

      - name: Verify Downloaded Artifact
        run: ls -la allure-report

      - name: Deploy Allure Report to GitHub Pages
        uses: actions/deploy-pages@v4
        with:
          folder: allure-report
